name: Fullstack-todo server flow

on:
  push:
    branches:
      - deploy

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_URL: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
    steps:
    - name: Setup SSH for EC2
      uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
      with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
    - name: Connect to EC2
      run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL
    - name: run scripts
      run: cd fullstack-todo-server &&
           git checkout deploy