name: GitHub Actions for Full-Stack front end

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          ssh-add private_key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key "${EC2_USERNAME}@${EC2_HOST}"
