name: Fullstack-todo server flow

on:
  push:
    branches:
      - deploy

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_URL: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
    steps:
    - name: get repo
      uses: actions/checkout@v2
      with:
        ref: deploy
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_EMAIL }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t fullstack-server .
    
    - name: Tag container
      run: docker tag fullstack-server uaral/full-stack-server:latest

    - name: Push Docker Image
      run: docker push uaral/full-stack-server:latest
    
    - name: Setup SSH for EC2
      uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
      with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
    - name: Connect to EC2
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL "\
        docker pull uaral/full-stack-server:latest &&
        docker stop full-stack-server || true &&
        docker rm full-stack-server || true &&
        docker run -d --name full-stack-server -p 80:80 uaral/full-stack-server:latest
        "